### ISSUE TITLE
Launcher not downloading 

### ISSUE THREAD

**Issue by MysteryRave** [ScottMichaud/YandereSimulatorLauncher2#4] opened 2020-04-07 00:24 UTC
It gives me a popup saying The website did not provide a download link that the launcher could recognize.
![Annotation 2020-04-06 172252](https://user-images.githubusercontent.com/63269628/78617185-74febd80-782b-11ea-98a9-0279d68a9ef3.jpg)

**Comment by ScottMichaud** [comment] 2020-04-07 00:28
Thanks for reporting!

This is a server-side issue. YandereDev is in the process of fixing it. It started on Thursday, April 2nd, 2020.

Until it's fixed, you will need to download from MediaFire on:
https://yanderedev.wordpress.com/downloads/

Mega might work, but the "Direct download from the official website" link will fail. (It will probably download a corrupted Zip archive that doesn't unpack.) It's all part of the same set of issues.

I will leave this issue open until the launcher works again.

**Comment by ScottMichaud** [comment] 2020-04-09 06:57
Looks like there was actually two issues.
The first one is the server-side issue, as seen in the screenshot. (The Yandere Simulator website was failing to send the download links.)
The second issue is with the launcher complaining about Mega. Apparently, on the same day as YandereDev had server issues, Mega changed their url format.
see: https://github.com/gpailler/MegaApiClient/issues/138
Naturally, I assumed it was all the first issue, so I kept waiting for the server to be fixed... but this should actually require a launcher update.

**Comment by ScottMichaud** [comment] 2020-04-09 19:52
While the original issue is caused by intermittent server failures, the rest of the issues are resolved in 2.8.0.

**Closed as completed by ScottMichaud** 2020-04-09 19:52 UTC
